name: rl_env
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.7
  - sympy
  - scipy
  - tensorflow-gpu=1.13.1
  - keras=2.2.4
  - jupyter
  - tqdm
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=10.2
  - pip:
        - gym
        - keras-rl
